# Generated by Django 4.2.6 on 2023-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosMicros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paradero',
            name='ubicacion',
            field=models.CharField(max_length=255),
        ),
    ]
