# Generated by Django 4.2.6 on 2023-12-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosMicros', '0002_alter_paradero_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='linea',
            name='buses',
            field=models.ManyToManyField(related_name='lineas', to='datosMicros.bus'),
        ),
    ]
