# Generated by Django 4.2.6 on 2023-12-05 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosMicros', '0004_micro_remove_linea_buses_delete_bus_linea_micros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='micros',
        ),
        migrations.AddField(
            model_name='micro',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='datosMicros.linea'),
        ),
    ]
