# Generated by Django 4.2.6 on 2023-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosMicros', '0005_remove_linea_micros_micro_linea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro',
            name='patente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
