# Generated by Django 4.2.6 on 2023-11-02 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmapsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paradero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParaderoRuta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.PositiveIntegerField()),
                ('paradero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmapsapi.paradero')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmapsapi.linea')),
                ('paraderos', models.ManyToManyField(through='gmapsapi.ParaderoRuta', to='gmapsapi.paradero')),
            ],
        ),
        migrations.DeleteModel(
            name='Distances',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.AddField(
            model_name='paraderoruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmapsapi.ruta'),
        ),
    ]
